### PR TITLE
perl dependency JSON-XS: set an explicit requirement on RPM version

### LINKED ISSUE #114: ccm 16.6.0-rc4 has missing dependencies on SL5
Trying to deploy 16.6.0-rc4 on a SL5 system, I got the following `ncm-spma` error:
```
2016/07/17-20:23:49 [ERROR] Failed synchronisation with upstream: Error: Package: ccm-16.6.0-rc4_1.noarch (quattor_16.6.0-rc4)
           Requires: perl(JSON::XS) >= 2.3.0
           Installed: perl-JSON-XS-2.30-1.el5.rf.x86_64 (installed)
               perl(JSON::XS) = 2.3
           Available: perl-JSON-XS-1.43-1.el5.x86_64 (sl5_epel)
               perl(JSON::XS) = 1.43

```
I am not completely sure why the installed version is considered lower than 2.3.0... It would be good to put the non standard dependency in `quattor_externals` YUM repo.

This is a showstopper for [16.6.0-rc4](https://github.com/quattor/release/issues/253) release.

### PR DESCRIPTION
**Pull request by jouvin**
Fixes #114 (YUM failure to match Perl-generated requirement on SL5)

This was intended to be a replacement for #115 (not working, see discussion for details) but ended up to be very close... #115 that must be closed when this one is merged. The summary is:
- Perl-generated requirement for version 2.3: doesn't work on SL6 as standard version is 2.27 and because Perl interprets versions as decimal numbers, 2.27 is less than 2.3...
- Perl requirement for v2.3 doesn't generate a RPM version requirement and thus YUM may install the EPEL version 1.47 that will not work, if a version > 2.3 is not present in any repo.

Successfully tested on both SL5 and SL6 (installation + ccm-fetch).

### CODE REVIEW

File: src/main/perl/Fetch/ProfileCache.pm [hunk 1]
```diff
@@ -52,7 +52,7 @@ use Digest::MD5 qw(md5_hex);
 use Readonly;
 use LC::Exception qw(SUCCESS);
 use XML::Parser;
-use JSON::XS v2.3.0 qw(decode_json encode_json);
+use JSON::XS v2.3 qw(decode_json encode_json);
```
Comment (stdweird) [inline src/main/perl/Fetch/ProfileCache.pm]: either use `v` here and below, or remove the `v` altogether
